### ISSUE TITLE
wrong type or Promise from RNCallKeep.getCalls()

### ISSUE THREAD

**Issue by folin03** [react-native-webrtc/react-native-callkeep#696] opened 2023-05-31 12:36 UTC
## Description

the function RNCallKeep.getCalls() returns array of objects but the types in CallKeep say it returns an object. Can you correct this? It causes problems down the line.

**Comment by ramijarrar** [comment] 2023-06-06 00:44
This is a duplicate of #680.

**Comment by ramijarrar** [comment] 2023-06-06 01:27
Created a PR to fix this #686.

**Closed** 2023-06-09 17:57 UTC
